### PR TITLE
Fix faulty indentation

### PR DESCRIPTION
**Pull request by teoljungberg**

### CODE REVIEW

**Comment by lgierth** [comment]
Thanks :cake:

**Comment by teoljungberg** [comment]
You're welcome :+1:

**Comment by lgierth** [comment]
What has your experience with promise.rb been so far? Unfortunately I haven't worked on any Ruby projects for the past 12 months...

**Comment by teoljungberg** [comment]
@lgierth I'm not actually using it, I was scratching an itch to see how hard it would be to build my own promise implementation. So I stumbled over your project and started poking around in it basically

**Pull request merged**
